const areaMap = {

  "河北": "Hebei",
  "山西": "Shanxi",
  "内蒙古": "Inner Mongolia",
  "辽宁": "Liaoning",
  "吉林": "Jilin",
  "黑龙江": "Heilongjiang",
  "江苏": "Jiangsu",
  "浙江": "Zhejiang",
  "安徽": "Anhui",
  "福建": "Fujian",
  "江西": "Jiangxi",
  "山东": "Shandong",
  "河南": "Henan",
  "湖北": "Hubei",
  "湖南": "Hunan",
  "广东": "Guangdong",
  "广西": "Guangxi",
  "海南": "Hainan",
  "四川": "Sichuan",
  "贵州": "Guizhou",
  "云南": "Yunnan",
  "西藏": "Tibet",
  "陕西": "Shanxi",
  "甘肃": "Gansu",
  "青海": "Qinghai",
  "宁夏": "Ningxia",
  "新疆": "Xinjiang",
  "台湾": "Taiwan",
  "北京": "Beijing",
  "上海": "Shanghai",
  "广州": "Guangzhou",
  "深圳": "Shenzhen",
  "成都": "Chengdu",
  "武汉": "Wuhan",
  "杭州": "Hangzhou",
  "南京": "Nanjing",
  "西安": "Xi'an",
  "重庆": "Chongqing",
  "天津": "Tianjin",
  "苏州": "Suzhou",
  "郑州": "Zhengzhou",
  "长沙": "Changsha",
  "沈阳": "Shenyang",
  "青岛": "Qingdao",
  "大连": "Dalian",
  "宁波": "Ningbo",
  "无锡": "Wuxi",
  "佛山": "Foshan",
  "东莞": "Dongguan",
  "唐山": "Tangshan",
  "烟台": "Yantai",
  "哈尔滨": "Harbin",
  "合肥": "Hefei",
  "昆明": "Kunming",
  "石家庄": "Shijiazhuang",
  "呼和浩特": "Hohhot",
  "南昌": "Nanchang",
  "乌鲁木齐": "Urumqi",
  "南宁": "Nanning",
  "长春": "Changchun",
  "福州": "Fuzhou",
  "厦门": "Xiamen",
  "贵阳": "Guiyang",
  "太原": "Taiyuan",
  "兰州": "Lanzhou",
  "西宁": "Xining",
  "银川": "Yinchuan",
  "海口": "Haikou",
  "拉萨": "Lhasa",
  "香港": "Hong Kong",
  "澳门": "Macao",
  "珠海": "Zhuhai",
  "汕头": "Shantou",
  "韶关": "Shaoguan",
  "河源": "Heyuan",
  "梅州": "Meizhou",
  "惠州": "Huizhou",
  "汕尾": "Shanwei",
  "江门": "Jiangmen",
  "阳江": "Yangjiang",
  "湛江": "Zhanjiang",
  "茂名": "Maoming",
  "肇庆": "Zhaoqing",
  "清远": "Qingyuan",
  "潮州": "Chaozhou",
  "揭阳": "Jieyang",
  "云浮": "Yunfu",
  "南宁": "Nanning",
  "柳州": "Liuzhou",
  "桂林": "Guilin",
  "梧州": "Wuzhou",
  "北海": "Beihai",
  "防城港": "Fangchenggang",
  "钦州": "Qinzhou",
  "贵港": "Guigang",
  "玉林": "Yulin",
  "百色": "Baise",
  "贺州": "Hezhou",
  "河池": "Hechi",
  "来宾": "Laibin",
  "崇左": "Chongzuo"
}
const weather = {
  "小雨": "icon-tianqi-xiaoyu",
  "中雨": "icon-tianqi-zhongyu",
  "大雨": "icon-tianqi-dayu",
  "阴天": "icon-yin",
  "晴天": "icon-tianqitubiao_qing",
  "雷雨": "icon-tianqi-leizhenyu",
  "多云": "icon-yin",
}
export default {
  areaMap,
  weather
};